//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJS_Server.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class OauthUser
    {
        public OauthUser()
        {
            this.Posts = new HashSet<Post>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public string OauthId { get; set; }
        public int OauthProviderId { get; set; }
        public string Email { get; set; }
    
        public virtual OauthProvider OauthProvider { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
    }
}
